plugins:
  - rubocop-internal_affairs

AllCops:
  NewCops: enable
  Exclude:
    - 'test/*'

Gemspec/RequireMFA:
  Enabled: false

# TODO: Find out what ruby version we actually require and then remove this.
Gemspec/RequiredRubyVersion:
  Enabled: false

InternalAffairs/NumblockHandler:
  Exclude:
    - 'lib/rubocop/cop/crystal/keyword_block_parameter.rb'

InternalAffairs/OnSendWithoutOnCSend:
  Exclude:
    - 'lib/rubocop/cop/crystal/require_at_top_level.rb'
    - 'lib/rubocop/cop/crystal/require_relative.rb'

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Naming/FileName:
  Enabled: false

Security/Eval:
  Exclude:
    - 'lib/rubocop/rspec/expect_match_crystal.rb'

Style/Documentation:
  Enabled: False

Style/FrozenStringLiteralComment:
  Enabled: False

Style/MutableConstant:
  Enabled: False
