require_relative 'crystal/file_extension'
require_relative 'crystal/interpolation_in_single_quotes'
require_relative 'crystal/method_name_starting_with_uppercase_letter'
require_relative 'crystal/require_relative'
